# CONFIGURE YOUR PROJECT SPECS HERE! 
PROJECT="nQb8or"
AUTHOR="O. KAUFMANN"
CONTRIBUTORS=" "
YEAR="$(date +%Y)"
VERSION="0.1"
REPO="github.com:kaufmanno/$PROJECT"
REMOTEMASTER="https://github.com/kaufmanno/$PROJECT/blob/master"
PIPFILE='Default'
ACTIVATEPIPENV=1
CLEANUP=1
ENTERPROJECT=1
RTDNAME=${PROJECT//_/-}
